//! Core Types
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_ERRORS = "GET_ERRORS";

//! Auth types
export const USER_LOADED = "ADMIN_LOADED";
export const USER_LOADING = "ADMIN_LOADING";
export const GET_USER = "GET_USER";
export const REFRESH_AUTH = "REFRESH_AUTH";
export const AUTH_ERRORS = "AUTH_ERRORS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_USER = "UPDATE_USER";
export const USER_ERRORS = "USER_ERRORS";

export const RETAILER_PRODUCTS_LOADED = "RETAILER_PRODUCTS_LOADED";
export const RETAILER_PRODUCTS_LOADING = "RETAILER_PRODUCTS_LOADING";
export const RETAILER_PRODUCTS_ERROR = "RETAILER_PRODUCTS_ERROR";
export const RETAILER_CATEGORIES_LOADED = "RETAILER_CATEGORIES_LOADED";
export const RETAILER_NEW_ARRIVALS = "RETAILER_NEW_ARRIVALS";
export const RETAILER_CATEGORY_PRODUCTS = "RETAILER_CATEGORY_PRODUCTS";

export const RETAILER_BANNERS_LOADED = "RETAILER_BANNERS_LOADED";
export const RETAILER_BANNERS_LOADING = "RETAILER_BANNERS_LOADING";
export const RETAILER_BANNERS_ERROR = "RETAILER_BANNERS_ERROR";

export const RETAILER_OFFERS_ERROR = "RETAILER_OFFERS_ERROR";
export const RETAILER_OFFERS_LOADED = "RETAILER_OFFERS_LOADED";
export const RETAILER_OFFERS_LOADING = "RETAILER_OFFERS_LOADING";
